# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Spring Boot & Gradle CI/CD v2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Grant execute permission for gradlew
      run: |
        cd seminar
        chmod +x gradlew
    
    - name: Build with Gradle
      run: |
        cd seminar
        ./gradlew bootJar
        
    - name: Make Directory for deliver
      run: mkdir deploy
      
    - name: Copy Jar
      run: cp ./seminar/build/libs/*.jar ./deploy/
      
    - name: Copy appspec
      run: cp ./seminar/appspec.yml ./deploy/
      
    - name: Copy shell
      run: cp ./seminar/scripts/bash/* ./deploy/
      
    - name: Make zip file
      run: zip -r -qq -j ./springboot-intro-build.zip ./deploy
      
    - name: Deliver to AWS S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp \
        --region ap-northeast-2 \
        --acl private \
        ./springboot-intro-build.zip s3://springboot-deploy-intro-waffle/
        
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
        --application-name springboot-intro \
        --deployment-group-name springboot-intro-deploy-group \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=springboot-deploy-intro-waffle,bundleType=zip,key=springboot-intro-build.zip \
        --region ap-northeast-2

        
