name: Run test with Gradle

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up MySQL
      uses: samin/mysql-action@v1
      with:
        charcter set server: 'utf8'
        mysql database: 'seminar'
        mysql user: 'waffle-spring'
        mysql password: 'wafflestudio'

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
          path: |
            ~/.gradle/caches
            ~/.gralde/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: |
        cd seminar
        chmod +x gradlew

    - name: Run test
      run: |
        cd seminar
        ./gradlew test --no-daemon

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: ${{ always() }}
      with:
        files: ./seminar/build/test-results/**/*.xml

    - name: Cleanup Gradle Cache
      run: |
        rm -f ~/.gradle/caches/modules-2/modules-2.lock
        rm -f ~/.gradle/caches/modules-2/gc.properties

